### ISSUE TITLE
Cannot open images

### ISSUE THREAD

**Issue by praetp** [schillij95/Crackle-Viewer#1]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/mnt/porsche/scrollprize/tools/Crackle-Viewer/view_gui.py", line 53, in menu_open_clicked
    self.load_images()
  File "/mnt/porsche/scrollprize/tools/Crackle-Viewer/view_gui.py", line 243, in load_images
    self.set_image(self.image_list[self.image_index])
  File "/mnt/porsche/scrollprize/tools/Crackle-Viewer/view_gui.py", line 416, in set_image
    self.pil_image = Image.open(filename)
  File "/home/spetsnaz/.local/lib/python3.10/site-packages/PIL/Image.py", line 3172, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/home/spetsnaz/.local/lib/python3.10/site-packages/PIL/Image.py", line 3159, in _open_core
    _decompression_bomb_check(im.size)
  File "/home/spetsnaz/.local/lib/python3.10/site-packages/PIL/Image.py", line 3068, in _decompression_bomb_check
    raise DecompressionBombError(
PIL.Image.DecompressionBombError: Image size (214763432 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```

**Comment by praetp** [comment]
PIL.Image.MAX_IMAGE_PIXELS = None

Solves it
